version: '3'
services:
  general:
    build: .
    working_dir: /general
    volumes:
      - general:/general
    environment:
      GITHUB_USER_NAME: ${GITHUB_USER_NAME}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_EMAIL: ${GITHUB_EMAIL}
      FCM_CREDENTIALS_JSON_BASE64: ${FCM_CREDENTIALS_JSON_BASE64}
      DATASTORE_PROJECT_ID: ness-local
      DATASTORE_EMULATOR_HOST: datastore:8000
    ports:
      - 3000:3000
      - 8080:8080
    tty: true
  datastore:
    image: singularities/datastore-emulator
    environment:
      DATASTORE_PROJECT_ID: ness-local
      DATASTORE_LISTEN_ADDRESS: 0.0.0.0:8000
    ports:
      - 8000:8000
  datastore-ui:
    image: skarpdev/google-datastore-ui:1.0.0
    environment:
      DSUI_PROJECT_ID: ness-local
      DSUI_PORT: 8001
      DSUI_DATASTORE_ENDPOINT: datastore:8000
    ports:
      - 8001:8001
    depends_on:
      - datastore
    links:
      - datastore
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms512m -Xmx512m
volumes:
  general:
